-- Showcase catalogue for the hosted demo.
--
-- GENERATED by `npm run generate:catalogue` from src/demo/catalogue.data.json.
-- Do not edit by hand — edit the catalogue data and regenerate. `npm run lint`
-- fails if this file drifts from the data.
--
-- NOT a migration and NOT seed.sql. Run it by hand, once, in the Supabase SQL
-- Editor of a demo project. It exists because a visitor lands on /shop without
-- logging in, so whatever is in there IS the pitch — and the headline feature
-- (wholesale price ladders) is invisible unless products actually have tiers.
--
-- Safe to re-run: every insert is keyed on slug and updates instead of
-- duplicating.
--
-- What it does:
--   1. archives whatever is currently on the storefront rather than deleting
--      it, so existing orders keep pointing at real product rows
--   2. adds 6 packaging categories
--   3. adds 36 products with pack sizes and minimums a wholesaler would
--      recognise, each pointing at the generated illustration the app ships in
--      public/images/supplymate/products/
--   4. gives most of them a price ladder, which is the whole point

begin;

-- 1. Clear the storefront without destroying history. `archived` hides a
--    product from /shop but leaves it readable from old orders.
update public.products set status = 'archived' where status <> 'archived';

-- 1b. products.sku is unique. An archived product still holding a SKU this
--     script is about to assign would block the insert, so release it — only
--     where it actually collides, and only on rows already off the storefront.
update public.products
   set sku = null
 where status = 'archived'
   and sku in ('SM-CUP-16-DOME','SM-CUP-22','SM-CUP-H8','SM-LID-95-BLK',
               'SM-LID-95-DOME','SM-CUP-CARRIER-4','SM-BOX-NOODLE','SM-BOX-BAGASSE-9',
               'SM-BOWL-PP-750','SM-TRAY-2C','SM-CUP-SOUP-16','SM-CUP-SAUCE-2',
               'SM-BAG-KRAFT-S','SM-BAG-KRAFT-M','SM-BAG-KRAFT-L','SM-BAG-GREASE',
               'SM-BAG-WINDOW','SM-BAG-FLAT','SM-LABEL-5030','SM-LABEL-4025',
               'SM-STICKER-40','SM-STICKER-FRAGILE','SM-LABEL-DATE','SM-ROLL-RECEIPT-58',
               'SM-BAR-SPOON','SM-BAR-SCOOP','SM-BAR-SHAKER','SM-BAR-PITCHER-600',
               'SM-BAR-PUMP','SM-BAR-MUDDLER','SM-ECO-PLATE-9','SM-ECO-BOWL-500',
               'SM-ECO-STRAW','SM-ECO-STIRRER','SM-ECO-CUTLERY','SM-ECO-LUNCH');

-- 2. Categories.
insert into public.categories (slug, name, description, sort_order, is_active) values
  ('cups-lids', 'แก้วและฝา',
   'แก้ว ฝา และอุปกรณ์สำหรับเครื่องดื่มเย็น', 1, true),
  ('food-containers', 'กล่องอาหาร',
   'กล่องและถ้วยสำหรับอาหารเดลิเวอรี', 2, true),
  ('paper-bags', 'ถุงกระดาษ',
   'ถุงกระดาษสำหรับร้านอาหารและเบเกอรี', 3, true),
  ('labels', 'ฉลากและสติกเกอร์',
   'ฉลากม้วนและสติกเกอร์สำหรับงานหน้าร้าน', 4, true),
  ('bar-tools', 'อุปกรณ์บาร์',
   'อุปกรณ์ชงและเสิร์ฟเครื่องดื่มสำหรับร้านค้า', 5, true),
  ('eco-packaging', 'บรรจุภัณฑ์รักษ์โลก',
   'บรรจุภัณฑ์ทางเลือกสำหรับลดพลาสติกใช้ครั้งเดียว', 6, true)
on conflict (slug) do update
  set name = excluded.name,
      description = excluded.description,
      sort_order = excluded.sort_order,
      is_active = true;

-- 3. Products. `price` is per package (per ลัง/แพ็ก/กล่อง/ม้วน) and excludes
--    VAT — the shop adds 7% at order time. `is_active` is never written here:
--    trg_products_sync_is_active derives it from status.
insert into public.products
  (slug, name, description, price, sku, stock_quantity, package_unit,
   units_per_package, min_order_quantity, sort_order, status, category_id)
select v.slug, v.name, v.description, v.price, v.sku, v.stock, v.unit,
       v.per_pack, v.moq, v.sort, 'active', c.id
from (values
  ('clear-cup-16oz', 'แก้วพลาสติกใส 16 ออนซ์พร้อมฝาโดม',
   'แก้ว PET ใสพร้อมฝาโดมสำหรับกาแฟเย็นและเครื่องดื่มปั่น',
   1650.00, 'SM-CUP-16-DOME', 42, 'carton', 1000, 1, 1, 'cups-lids'),
  ('pet-cup-22oz', 'แก้ว PET ใส 22 ออนซ์',
   'แก้วใสทรงสูงสำหรับชาเย็นและเครื่องดื่มขนาดใหญ่',
   1780.00, 'SM-CUP-22', 31, 'carton', 1000, 1, 2, 'cups-lids'),
  ('hot-cup-8oz', 'แก้วกระดาษร้อน 8 ออนซ์',
   'แก้วกระดาษเคลือบสำหรับกาแฟร้อนและชาร้อน',
   1240.00, 'SM-CUP-H8', 47, 'carton', 1000, 1, 3, 'cups-lids'),
  ('black-flat-lid-95mm', 'ฝาเรียบสีดำ 95 มม.',
   'ฝาปิดแก้วทรงเรียบพร้อมช่องเสียบหลอด',
   720.00, 'SM-LID-95-BLK', 58, 'carton', 1000, 1, 4, 'cups-lids'),
  ('dome-lid-95mm', 'ฝาโดมใส 95 มม.',
   'ฝาโดมใสสำหรับเครื่องดื่มปั่นและเมนูท็อปปิงสูง',
   780.00, 'SM-LID-95-DOME', 51, 'carton', 1000, 1, 5, 'cups-lids'),
  ('cup-carrier-4', 'ถาดหิ้วแก้ว 4 ช่อง',
   'ถาดกระดาษหิ้วแก้ว 4 ช่องสำหรับงานเดลิเวอรี',
   960.00, 'SM-CUP-CARRIER-4', 23, 'pack', 200, 2, 6, 'cups-lids'),
  ('kraft-noodle-box', 'กล่องคราฟท์ใส่อาหารทรงสูง',
   'กล่องเคลือบกันซึมสำหรับข้าวและเส้น มีสองขนาดให้เลือก',
   890.00, 'SM-BOX-NOODLE', 26, 'carton', 300, 1, 7, 'food-containers'),
  ('bagasse-clamshell-9in', 'กล่องชานอ้อย 9 นิ้ว',
   'กล่องฝาพับจากเยื่อชานอ้อยสำหรับอาหารจานเดียว',
   980.00, 'SM-BOX-BAGASSE-9', 24, 'carton', 200, 1, 8, 'food-containers'),
  ('pp-microwave-bowl-750', 'ถ้วยพลาสติก PP เข้าไมโครเวฟ 750 มล.',
   'ถ้วย PP ฝาล็อกแน่น เข้าไมโครเวฟได้',
   1180.00, 'SM-BOWL-PP-750', 28, 'carton', 300, 1, 9, 'food-containers'),
  ('rice-tray-2-compartment', 'ถาดอาหาร 2 ช่องพร้อมฝา',
   'ถาดอาหาร 2 ช่องพร้อมฝาสำหรับข้าวกล่อง',
   1420.00, 'SM-TRAY-2C', 21, 'carton', 300, 1, 10, 'food-containers'),
  ('soup-cup-16oz', 'ถ้วยซุปกระดาษ 16 ออนซ์พร้อมฝา',
   'ถ้วยกระดาษทรงสูงพร้อมฝาสำหรับซุปและโจ๊ก',
   1090.00, 'SM-CUP-SOUP-16', 30, 'carton', 500, 1, 11, 'food-containers'),
  ('sauce-cup-2oz', 'ถ้วยน้ำจิ้ม 2 ออนซ์พร้อมฝา',
   'ถ้วยใสขนาดเล็กพร้อมฝาปิดแน่นสำหรับซอสและท็อปปิง',
   1320.00, 'SM-CUP-SAUCE-2', 37, 'carton', 2000, 1, 12, 'food-containers'),
  ('kraft-bag-small', 'ถุงกระดาษคราฟท์หูหิ้ว ขนาด S',
   'ถุงทรงตั้งสำหรับขนมและสินค้าเบา',
   1150.00, 'SM-BAG-KRAFT-S', 19, 'carton', 500, 1, 13, 'paper-bags'),
  ('kraft-bag-medium', 'ถุงกระดาษคราฟท์หูหิ้ว ขนาด M',
   'ถุงทรงตั้งสำหรับกล่องอาหารและชุดของฝาก',
   1390.00, 'SM-BAG-KRAFT-M', 22, 'carton', 500, 1, 14, 'paper-bags'),
  ('kraft-bag-large', 'ถุงกระดาษคราฟท์หูหิ้ว ขนาด L',
   'ถุงทรงตั้งขนาดใหญ่สำหรับชุดอาหารหลายกล่อง',
   1620.00, 'SM-BAG-KRAFT-L', 17, 'carton', 500, 1, 15, 'paper-bags'),
  ('greaseproof-snack-bag', 'ถุงกระดาษกันมันสำหรับของทอด',
   'ถุงเปิดปากสำหรับเฟรนช์ฟรายส์และของว่าง',
   760.00, 'SM-BAG-GREASE', 35, 'carton', 1000, 1, 16, 'paper-bags'),
  ('bakery-window-bag', 'ถุงกระดาษหน้าต่างใสสำหรับเบเกอรี',
   'ถุงกระดาษมีหน้าต่างใสสำหรับขนมอบและเบเกอรี',
   880.00, 'SM-BAG-WINDOW', 26, 'carton', 1000, 1, 17, 'paper-bags'),
  ('delivery-flat-bag', 'ถุงกระดาษก้นแบนสำหรับเดลิเวอรี',
   'ถุงกระดาษก้นแบนวางตั้งได้สำหรับงานส่งอาหาร',
   1040.00, 'SM-BAG-FLAT', 24, 'carton', 1000, 1, 18, 'paper-bags'),
  ('thermal-label-50x30', 'ฉลากความร้อน 50 × 30 มม.',
   'ฉลากเปล่าสำหรับพิมพ์ราคาและวันที่ผลิต',
   95.00, 'SM-LABEL-5030', 120, 'roll', 1000, 6, 19, 'labels'),
  ('thermal-label-40x25', 'ฉลากความร้อน 40 × 25 มม.',
   'ฉลากความร้อนขนาดเล็กสำหรับติดแก้วและถ้วย',
   82.00, 'SM-LABEL-4025', 140, 'roll', 1000, 6, 20, 'labels'),
  ('blank-sticker-roll-40mm', 'สติกเกอร์เปล่าทรงกลม 40 มม.',
   'สติกเกอร์กระดาษขาวสำหรับปิดถุงและติดแก้ว',
   120.00, 'SM-STICKER-40', 86, 'roll', 500, 4, 21, 'labels'),
  ('fragile-sticker-roll', 'สติกเกอร์ระวังแตก',
   'สติกเกอร์เตือนสำหรับพัสดุและกล่องที่ต้องระวัง',
   145.00, 'SM-STICKER-FRAGILE', 72, 'roll', 500, 3, 22, 'labels'),
  ('date-label-pack', 'สติกเกอร์ระบุวันผลิตแบบเขียน',
   'สติกเกอร์สำหรับจัดการวัตถุดิบและวันหมดอายุ',
   180.00, 'SM-LABEL-DATE', 64, 'pack', 500, 2, 23, 'labels'),
  ('receipt-roll-58mm', 'กระดาษใบเสร็จ 58 มม.',
   'กระดาษความร้อนสำหรับเครื่องพิมพ์ใบเสร็จหน้าร้าน',
   210.00, 'SM-ROLL-RECEIPT-58', 95, 'pack', 10, 2, 24, 'labels'),
  ('stainless-bar-spoon', 'ช้อนบาร์สเตนเลสด้ามเกลียว',
   'ช้อนด้ามยาวสำหรับคนเครื่องดื่มและตวงชั้น',
   540.00, 'SM-BAR-SPOON', 18, 'pack', 12, 1, 25, 'bar-tools'),
  ('ice-scoop-stainless', 'ที่ตักน้ำแข็งสเตนเลส',
   'ที่ตักน้ำแข็งสเตนเลสสำหรับงานบาร์และหน้าร้าน',
   620.00, 'SM-BAR-SCOOP', 26, 'pack', 12, 1, 26, 'bar-tools'),
  ('cocktail-shaker', 'เชคเกอร์สเตนเลส',
   'เชคเกอร์สามชิ้นสำหรับบาร์กาแฟและเครื่องดื่ม มีสองขนาด',
   2160.00, 'SM-BAR-SHAKER', 15, 'case', 24, 1, 27, 'bar-tools'),
  ('milk-pitcher-600ml', 'เหยือกตีฟองนม 600 มล.',
   'เหยือกสเตนเลสสำหรับตีฟองนมและเทลาย',
   1180.00, 'SM-BAR-PITCHER-600', 20, 'pack', 12, 1, 28, 'bar-tools'),
  ('syrup-pump-pack', 'หัวปั๊มไซรัปมาตรฐาน',
   'หัวปั๊มปริมาณคงที่สำหรับขวดไซรัปร้านกาแฟ',
   390.00, 'SM-BAR-PUMP', 43, 'pack', 6, 1, 29, 'bar-tools'),
  ('muddler-wood', 'ไม้บดสมุนไพรด้ามไม้',
   'ไม้บดสมุนไพรและผลไม้สำหรับเครื่องดื่มสด',
   480.00, 'SM-BAR-MUDDLER', 22, 'pack', 12, 1, 30, 'bar-tools'),
  ('bagasse-plate-9in', 'จานชานอ้อย 9 นิ้ว',
   'จานเยื่อธรรมชาติสำหรับอาหารจัดเลี้ยงและงานอีเวนต์',
   1250.00, 'SM-ECO-PLATE-9', 29, 'carton', 500, 1, 31, 'eco-packaging'),
  ('kraft-soup-bowl-500', 'ชามกระดาษคราฟท์ 500 มล.',
   'ชามกระดาษคราฟท์พร้อมฝาสำหรับซุปและอาหารร้อน',
   1120.00, 'SM-ECO-BOWL-500', 25, 'carton', 500, 1, 32, 'eco-packaging'),
  ('compostable-straw', 'หลอดย่อยสลายได้',
   'หลอดจากวัสดุย่อยสลายได้ มีขนาดมาตรฐานและขนาดชานม',
   980.00, 'SM-ECO-STRAW', 33, 'case', 1000, 1, 33, 'eco-packaging'),
  ('wooden-stirrer', 'ไม้คนกาแฟ',
   'ไม้คนเครื่องดื่มแบบใช้ครั้งเดียว ย่อยสลายได้',
   340.00, 'SM-ECO-STIRRER', 40, 'case', 2000, 1, 34, 'eco-packaging'),
  ('bioplastic-cutlery-set', 'ชุดช้อนส้อมไบโอพลาสติก',
   'ชุดช้อนส้อมบรรจุแยกสำหรับอาหารเดลิเวอรี',
   1480.00, 'SM-ECO-CUTLERY', 27, 'case', 500, 1, 35, 'eco-packaging'),
  ('paper-lunch-box-eco', 'กล่องกระดาษคราฟท์รักษ์โลก 1 ช่อง',
   'กล่องกระดาษคราฟท์หนึ่งช่องสำหรับข้าวกล่องรักษ์โลก',
   1310.00, 'SM-ECO-LUNCH', 23, 'carton', 300, 1, 36, 'eco-packaging')
) as v(slug, name, description, price, sku, stock, unit, per_pack, moq, sort, category_slug)
join public.categories c on c.slug = v.category_slug
on conflict (slug) do update
  set name = excluded.name, description = excluded.description, price = excluded.price,
      sku = excluded.sku, stock_quantity = excluded.stock_quantity,
      package_unit = excluded.package_unit, units_per_package = excluded.units_per_package,
      min_order_quantity = excluded.min_order_quantity, sort_order = excluded.sort_order,
      status = 'active', category_id = excluded.category_id;

-- 4. Product images. The paths are root-relative assets the app itself ships,
--    not storage objects — resolveImageUrl() passes a leading-slash path
--    through untouched. Cleared first so a re-run cannot stack duplicates:
--    product_images has no unique key to conflict on.
delete from public.product_images i
 using public.products p
 where p.id = i.product_id
   and p.slug in ('clear-cup-16oz','pet-cup-22oz','hot-cup-8oz',
                 'black-flat-lid-95mm','dome-lid-95mm','cup-carrier-4',
                 'kraft-noodle-box','bagasse-clamshell-9in','pp-microwave-bowl-750',
                 'rice-tray-2-compartment','soup-cup-16oz','sauce-cup-2oz',
                 'kraft-bag-small','kraft-bag-medium','kraft-bag-large',
                 'greaseproof-snack-bag','bakery-window-bag','delivery-flat-bag',
                 'thermal-label-50x30','thermal-label-40x25','blank-sticker-roll-40mm',
                 'fragile-sticker-roll','date-label-pack','receipt-roll-58mm',
                 'stainless-bar-spoon','ice-scoop-stainless','cocktail-shaker',
                 'milk-pitcher-600ml','syrup-pump-pack','muddler-wood',
                 'bagasse-plate-9in','kraft-soup-bowl-500','compostable-straw',
                 'wooden-stirrer','bioplastic-cutlery-set','paper-lunch-box-eco');

insert into public.product_images (product_id, storage_path, alt, sort_order)
select p.id, v.storage_path, v.alt, 0
from (values
  ('clear-cup-16oz', '/images/supplymate/products/clear-cup-16oz.svg', 'แก้วพลาสติกใส 16 ออนซ์พร้อมฝาโดม'),
  ('pet-cup-22oz', '/images/supplymate/products/pet-cup-22oz.svg', 'แก้ว PET ใส 22 ออนซ์'),
  ('hot-cup-8oz', '/images/supplymate/products/hot-cup-8oz.svg', 'แก้วกระดาษร้อน 8 ออนซ์'),
  ('black-flat-lid-95mm', '/images/supplymate/products/black-flat-lid-95mm.svg', 'ฝาเรียบสีดำ 95 มม.'),
  ('dome-lid-95mm', '/images/supplymate/products/dome-lid-95mm.svg', 'ฝาโดมใส 95 มม.'),
  ('cup-carrier-4', '/images/supplymate/products/cup-carrier-4.svg', 'ถาดหิ้วแก้ว 4 ช่อง'),
  ('kraft-noodle-box', '/images/supplymate/products/kraft-noodle-box.svg', 'กล่องคราฟท์ใส่อาหารทรงสูง'),
  ('bagasse-clamshell-9in', '/images/supplymate/products/bagasse-clamshell-9in.svg', 'กล่องชานอ้อย 9 นิ้ว'),
  ('pp-microwave-bowl-750', '/images/supplymate/products/pp-microwave-bowl-750.svg', 'ถ้วยพลาสติก PP เข้าไมโครเวฟ 750 มล.'),
  ('rice-tray-2-compartment', '/images/supplymate/products/rice-tray-2-compartment.svg', 'ถาดอาหาร 2 ช่องพร้อมฝา'),
  ('soup-cup-16oz', '/images/supplymate/products/soup-cup-16oz.svg', 'ถ้วยซุปกระดาษ 16 ออนซ์พร้อมฝา'),
  ('sauce-cup-2oz', '/images/supplymate/products/sauce-cup-2oz.svg', 'ถ้วยน้ำจิ้ม 2 ออนซ์พร้อมฝา'),
  ('kraft-bag-small', '/images/supplymate/products/kraft-bag-small.svg', 'ถุงกระดาษคราฟท์หูหิ้ว ขนาด S'),
  ('kraft-bag-medium', '/images/supplymate/products/kraft-bag-medium.svg', 'ถุงกระดาษคราฟท์หูหิ้ว ขนาด M'),
  ('kraft-bag-large', '/images/supplymate/products/kraft-bag-large.svg', 'ถุงกระดาษคราฟท์หูหิ้ว ขนาด L'),
  ('greaseproof-snack-bag', '/images/supplymate/products/greaseproof-snack-bag.svg', 'ถุงกระดาษกันมันสำหรับของทอด'),
  ('bakery-window-bag', '/images/supplymate/products/bakery-window-bag.svg', 'ถุงกระดาษหน้าต่างใสสำหรับเบเกอรี'),
  ('delivery-flat-bag', '/images/supplymate/products/delivery-flat-bag.svg', 'ถุงกระดาษก้นแบนสำหรับเดลิเวอรี'),
  ('thermal-label-50x30', '/images/supplymate/products/thermal-label-50x30.svg', 'ฉลากความร้อน 50 × 30 มม.'),
  ('thermal-label-40x25', '/images/supplymate/products/thermal-label-40x25.svg', 'ฉลากความร้อน 40 × 25 มม.'),
  ('blank-sticker-roll-40mm', '/images/supplymate/products/blank-sticker-roll-40mm.svg', 'สติกเกอร์เปล่าทรงกลม 40 มม.'),
  ('fragile-sticker-roll', '/images/supplymate/products/fragile-sticker-roll.svg', 'สติกเกอร์ระวังแตก'),
  ('date-label-pack', '/images/supplymate/products/date-label-pack.svg', 'สติกเกอร์ระบุวันผลิตแบบเขียน'),
  ('receipt-roll-58mm', '/images/supplymate/products/receipt-roll-58mm.svg', 'กระดาษใบเสร็จ 58 มม.'),
  ('stainless-bar-spoon', '/images/supplymate/products/stainless-bar-spoon.svg', 'ช้อนบาร์สเตนเลสด้ามเกลียว'),
  ('ice-scoop-stainless', '/images/supplymate/products/ice-scoop-stainless.svg', 'ที่ตักน้ำแข็งสเตนเลส'),
  ('cocktail-shaker', '/images/supplymate/products/cocktail-shaker.svg', 'เชคเกอร์สเตนเลส'),
  ('milk-pitcher-600ml', '/images/supplymate/products/milk-pitcher-600ml.svg', 'เหยือกตีฟองนม 600 มล.'),
  ('syrup-pump-pack', '/images/supplymate/products/syrup-pump-pack.svg', 'หัวปั๊มไซรัปมาตรฐาน'),
  ('muddler-wood', '/images/supplymate/products/muddler-wood.svg', 'ไม้บดสมุนไพรด้ามไม้'),
  ('bagasse-plate-9in', '/images/supplymate/products/bagasse-plate-9in.svg', 'จานชานอ้อย 9 นิ้ว'),
  ('kraft-soup-bowl-500', '/images/supplymate/products/kraft-soup-bowl-500.svg', 'ชามกระดาษคราฟท์ 500 มล.'),
  ('compostable-straw', '/images/supplymate/products/compostable-straw.svg', 'หลอดย่อยสลายได้'),
  ('wooden-stirrer', '/images/supplymate/products/wooden-stirrer.svg', 'ไม้คนกาแฟ'),
  ('bioplastic-cutlery-set', '/images/supplymate/products/bioplastic-cutlery-set.svg', 'ชุดช้อนส้อมไบโอพลาสติก'),
  ('paper-lunch-box-eco', '/images/supplymate/products/paper-lunch-box-eco.svg', 'กล่องกระดาษคราฟท์รักษ์โลก 1 ช่อง')
) as v(slug, storage_path, alt)
join public.products p on p.slug = v.slug;

-- 5. Price ladders. Percentages rather than fixed amounts so every product's
--    ladder stays sensible against its own base price. The last product in
--    each category is left without one on purpose: a catalogue where
--    everything has tiers hides what the "มีราคาขั้นบันได" filter and the
--    "ยังไม่มีขั้น" admin badge are actually for.
delete from public.product_price_tiers t
 using public.products p
 where p.id = t.product_id;

insert into public.product_price_tiers (product_id, min_quantity, unit_price)
select p.id, s.min_qty, round(p.price * s.factor, 2)
from public.products p
join (values
  (5, 0.96), (10, 0.93), (20, 0.90), (50, 0.86), (100, 0.82)
) as s(min_qty, factor) on true
where p.slug in ('clear-cup-16oz','pet-cup-22oz','hot-cup-8oz',
                 'black-flat-lid-95mm','dome-lid-95mm','kraft-noodle-box',
                 'bagasse-clamshell-9in','pp-microwave-bowl-750','rice-tray-2-compartment',
                 'soup-cup-16oz','kraft-bag-small','kraft-bag-medium',
                 'kraft-bag-large','greaseproof-snack-bag','bakery-window-bag',
                 'date-label-pack','stainless-bar-spoon','ice-scoop-stainless',
                 'cocktail-shaker','milk-pitcher-600ml','syrup-pump-pack',
                 'bagasse-plate-9in','kraft-soup-bowl-500','compostable-straw',
                 'wooden-stirrer','bioplastic-cutlery-set')
  and s.min_qty > p.min_order_quantity;

-- The higher-MOQ items get a ladder that starts above their own minimum,
-- because a tier at or below it is unreachable and the trigger rejects it.
insert into public.product_price_tiers (product_id, min_quantity, unit_price)
select p.id, s.min_qty, round(p.price * s.factor, 2)
from public.products p
join (values
  (12, 0.95), (24, 0.91), (60, 0.87), (120, 0.83)
) as s(min_qty, factor) on true
where p.slug in ('thermal-label-50x30','thermal-label-40x25','blank-sticker-roll-40mm',
                 'fragile-sticker-roll')
  and s.min_qty > p.min_order_quantity;

commit;

-- What the storefront should look like afterwards.
select p.name,
       p.package_unit || ' · ' || p.units_per_package || ' ชิ้น' as pack,
       p.price,
       p.price_per_piece,
       count(distinct t.id) as tiers,
       count(distinct i.id) as images
  from public.products p
  left join public.product_price_tiers t on t.product_id = p.id
  left join public.product_images i on i.product_id = p.id
 where p.status = 'active'
 group by p.id, p.name, p.package_unit, p.units_per_package, p.price, p.price_per_piece, p.sort_order
 order by p.sort_order;
